"""Automatic startup migration

Revision ID: a70f3070460e
Revises: fd3839d826bc
Create Date: 2026-07-03 11:37:51.150181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70f3070460e'
down_revision = 'fd3839d826bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
