"""Automatic startup migration

Revision ID: f4e69e2cc117
Revises: 8e8dadea4edd
Create Date: 2026-07-03 11:33:20.062983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e69e2cc117'
down_revision = '8e8dadea4edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_seed', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('avatar_seed')

    # ### end Alembic commands ###
