"""Automatic startup migration

Revision ID: fd3839d826bc
Revises: f4e69e2cc117
Create Date: 2026-07-03 11:37:24.064596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3839d826bc'
down_revision = 'f4e69e2cc117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
